//import { Children } from 'react';
//import myContext from './Helper/Context';
//import "./globals.css";

export const metadata = {
  title: "To-do-list",
  //description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>{children}</body>
      {/* <myContext>{children}</myContext> */}
    </html>
  );
}
